export type BobertConfig = {
	bot: {
		token: string;
		guild: string;
		category: string;
		blacklisted_channels: string[] | null;
		scoreboard_channel: string;
		autogenerated: {
			scoreboard_message: string;
		} | null;
	};
	event: {
		teams: string[];
		items: BobertItem[];
	};
};

export type BobertItem = {
	name: string;
	emoji: string;
	response: string;
	net_score: number;
	auto_react: boolean | null;
	weight: number | null;
};
