import { Listener } from "@sapphire/framework";
import { BobertClient } from "../lib/client";
import { ChannelType, EmbedBuilder } from "discord.js";
import updateEmbed from "../lib/updateEmbed";

export class InitializeLeaderboardListener extends Listener {
	public constructor(context: Listener.Context, options: Listener.Options) {
		super(context, {
			...options,
			name: "initializeLeaderboard",
			once: true,
			event: "ready",
		});
	}

	public async run(client: BobertClient) {
		// if the ID isn't already written to the config we need to make the embed
		if (!this.container.config.bot.autogenerated)
			await this.createEmbed(client);

		await updateEmbed(client);
	}

	private async createEmbed(client: BobertClient) {
		const channel = await client.channels.fetch(
			this.container.config.bot.scoreboard_channel,
		);

		if (channel?.type !== ChannelType.GuildText) {
			this.container.logger.fatal(
				"Provided scoreboard channel is not a text channel. Exiting.",
			);
			process.exit(1);
		}

		const message = await channel.send("Scoreboard loading...");

		client.writeEmbedSnowflake(message.id);
	}
}
