import { Events, Listener, SapphireClient } from "@sapphire/framework";
import { ChannelType } from "discord.js";
import { writeEmbedSnowflake } from "../lib/config";
import updateEmbed from "../lib/updateEmbed";

export class InitializeLeaderboardListener extends Listener {
	public constructor(
		context: Listener.LoaderContext,
		options: Listener.Options,
	) {
		super(context, {
			...options,
			name: "initializeLeaderboard",
			once: true,
			event: Events.ClientReady,
		});
	}

	public async run(client: SapphireClient) {
		// if the ID isn't already written to the config we need to make the embed
		if (!this.container.config.bot.autogenerated)
			await this.createEmbed(client);

		await updateEmbed();
	}

	private async createEmbed(client: SapphireClient) {
		const channel = await client.channels.fetch(
			this.container.config.bot.scoreboard_channel,
		);

		if (channel?.type !== ChannelType.GuildText) {
			this.container.logger.fatal(
				"Provided scoreboard channel is not a text channel. Exiting.",
			);
			process.exit(1);
		}

		const message = await channel.send("Scoreboard loading...");

		writeEmbedSnowflake(message.id);
	}
}
